### PR TITLE
New modular transport base classes

### PR DESCRIPTION
**Pull request by akbad**
A few pointers:

- Ignore the UDP-* files for now
- I need some clarification from Kimiya about how some stream methods are meant to work, then will implement those
- I'm not too sure, but I'm guessing some methods from the Parsers and Schedulers can be implemented here, let me know if that is the case
- There are a few comments in the code that contain some lingering but non-urgent questions

### CODE REVIEW

**Comment by Josh-Jo1** [comment]
LGTM
Please remove the UDP files from this PR since those aren't complete yet. We can make another PR later

**Review by pvvm — COMMENTED** [review]
I don't know how much about ns3, but at least the main modules of MTP, EPs, context, dispatcher, and event scheduler look good to me

**Comment by kymmt80** [comment]
Now that flow_id is supposed to be int, I think it is better to remove those templates from the definition of event constructors in "event-mt.cc"

**Comment by kymmt80** [comment]
For the scheduler, I think we need an enqueue function as well (The top module needs to have a way to insert elements into queues) this function wont be virtual, since we can implement it here. We must receive events and enqueue them based on their type.

**Comment by kymmt80** [comment]
another comment for the scheduler, it is better to write a top level function that can be called from outside, lets call it get_next_event. This function should return the result of next_event(next_flow()).

**Comment by kymmt80** [comment]
Regarding your question, we can also implement the next_event and next_flow functions here(Since we expect them to be fixed). You can use a simple round-robin algorithm, same for the next_pkt and next_feedback in in tx modules

**Review by kymmt80 — CHANGES_REQUESTED** [review]
I left some comments above about the changes. Other parts look good. Thanks!

**Comment by akbad** [comment]
> Now that flow_id is supposed to be int, I think it is better to remove those templates from the definition of event constructors in "event-mt.cc"

Good catch, thanks!

**Comment by kymmt80** [comment]
Another comment: I noticed that you added the  `MTContext c` as input to the `process` method in `MTEventProcessor`. The context is supposed to be in the `EventProcessorOutput` class, so you can remove `MTContext c` from the method inputs.

**Review by kymmt80 — APPROVED** [review]
Looks good.

**Pull request merged**
